ReservationSalle/Controllers/ClientController.cs
using BLL;
using DAL.models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace ReservationSalle.Controllers
{
    [Authorize(Roles = "User")]

    public class ClientController : Controller
    {

        private readonly SalleService _salleService;
        private readonly ReservationService _reservationService;

        public ClientController(SalleService salleService, ReservationService reservationService)
        {
            _salleService = salleService;
            _reservationService = reservationService;
        }

        [HttpGet]
        public IActionResult Salles()
        {
            return View(_salleService.getAll());
        }

        [HttpGet]
        public IActionResult MesReservations(int id)
        {
            return View(_salleService.getReservations(id));
        }

        [HttpGet]
        public IActionResult Reserver(int id)
        {
            return View(_salleService.getById(id));
        }

        [HttpPost]
        public IActionResult ReserverPost(
                                           [FromForm(Name = "date")] DateTime date,
                                           [FromForm(Name = "nbrHeure")] int nbrHeure,
                                           [FromForm(Name = "salleId")] int salleId,
                                           [FromForm(Name = "personneId")] int personneId
                                            )
        {
            Reservation reservation = new Reservation();
            reservation.date = date;
            reservation.nbrHeure = nbrHeure;
            reservation.salleId = salleId;
            reservation.personneId = personneId;
            _reservationService.create(reservation);
            return RedirectToAction("Salles");
        }
    }
}

ReservationSalle/Controllers/ReservationController.cs
using BLL;
using DAL.models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace ReservationSalle.Controllers
{
    [Authorize(Roles = "Admin")]
    public class ReservationController : Controller
    {
        private readonly ReservationService _reservationService;

        public ReservationController(ReservationService reservationService)
        {
            this._reservationService = reservationService;
        }

        public IActionResult Index()
        {
            return View(_reservationService.getAll());
        }
        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Add(Reservation reservation)
        {
            _reservationService.create(reservation);

            return RedirectToAction("Index");

        }


        [HttpGet]
        public IActionResult DeleteView(int id)
        {
            return View("Delete", _reservationService.getById(id));
        }

        [HttpPost]
        public IActionResult Delete(int id)
        {
            _reservationService.delete(id);

            return RedirectToAction("Index");

        }

        [HttpGet]
        public IActionResult UpdateView(int id)
        {
            return View("Update", _reservationService.getById(id));
        }




        [HttpPost]
        public IActionResult Update(Reservation reservation)
        {
            _reservationService.update(reservation);
            return RedirectToAction("Index");
        }





    }
}

ReservationSalle/Controllers/SalleController.cs
using BLL;
using DAL.models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace ReservationSalle.Controllers
{
    [Authorize(Roles = "Admin")]
    public class SalleController : Controller
    {
        private readonly SalleService _salleService;

        public SalleController(SalleService salleService)
        {
           this._salleService = salleService;
        }

        public IActionResult Index()
        {
            return View(_salleService.getAll());
        }
        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Add(Salle salle)
        {
            _salleService.create(salle);

            return RedirectToAction("Index");

        }


        [HttpGet]
        public IActionResult DeleteView(int id)
        {
            return View("Delete", _salleService.getById(id));
        }

        [HttpPost]
        public IActionResult Delete(int id)
        {
            _salleService.delete(id);

            return RedirectToAction("Index");

        }

        [HttpGet]
        public IActionResult UpdateView(int id)
        {
            return View("Update", _salleService.getById(id));
        }




        [HttpPost]
        public IActionResult Update(Salle salle)
        {
            _salleService.update(salle);
            return RedirectToAction("Index");
        }





    }
}

ReservationSalle/Views/Shared/_Layout.cshtml
@using System.Security.Claims
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ReservationSalle</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ReservationSalle.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-dark border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand text-light" href="#" >ReservationSalle</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                    {
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Salle" asp-action="Index">Salles</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Personne" asp-action="Index">Personnes</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Reservation" asp-action="Index">Reservations</a>
                            </li>
                        </ul>
                        <ul class="navbar-nav mr-0">
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Personne" asp-action="Logout">Log out</a>
                            </li>
                        </ul>
                    }
                    else if (User.Identity.IsAuthenticated && User.IsInRole("User"))
                            {
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Client" asp-action="Salles">Salles</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Client" asp-action="MesReservations" asp-route-id="@User.FindFirstValue(ClaimTypes.NameIdentifier)">Mes reservations</a>
                        </li>
                        </ul>
                        <ul class="navbar-nav mr-0">
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Personne" asp-action="Logout">Log out</a>
                            </li>
                        </ul>
                            }else{
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Personne" asp-action="Login">Log in</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Personne" asp-action="Sign">Sign up</a>
                            </li>
                        </ul>
                                 }
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - ReservationSalle - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>